---
- name: Add SSH public key to authorized_keys
  hosts: all
  become: yes

  vars:
    target_user: dpadmin
    public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDYN5J9IolD0K9laodN3jAw0B1N8c0989749ZC9dLkO3/9wD5Laac3t9EHrZcFZ53WOSG4JHckl0XlET/i33rPs1hxlcPcWPGsHONiIQNbkSfMrYq1en2f1Se2KcjmVa+qjxij5TfrtIMDQRDwqBdtu2j1RhmIfCYzFZzT6E3sN+/ynnNN3trpIFn3XFM26GYF7nbtSOvYtqZ5KN7wzA+diw8EyBbHIfTJwbNM5rXot7aUyo2mA826OigTRer1OG9grWUOEYfwJ/a8wmNhoZOIMxhirUBdmOYjUkvdjFG2EUW0j8shWxVQaeKOkCb8gmF/XZ/n8b8EXcr8QTQH2/GKERgOXyQY8rom9eJ99h/IoFfCPfMRs5tNJrO+kEij2WX+uTExFqP2BgyoewjZXPvIt8rcvOEkS36NxVqgB0vYRPwg82xPonaWuMn4ZBZWYPAPor7R1zFepAutIf57Ts73TMr0XzNFI5IY09gKx64GCq6fSR9LnavNkB9pnjHEyoqM= dpadmin@MYSBCPRHELSAT01"

  tasks:
    - name: Ensure .ssh directory exists
      file:
        path: "/home/{{ target_user }}/.ssh"
        state: directory
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0700'

    - name: Add public key to authorized_keys
      authorized_key:
        user: "{{ target_user }}"
        state: present
        key: "{{ public_key }}"

    - name: Set authorized_keys permissions
      file:
        path: "/home/{{ target_user }}/.ssh/authorized_keys"
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0600'
