---
- name: Create dpadmin user
  hosts: all
  become: yes

  vars:
    dpadmin_password: "Dpadmin$2026"

  tasks:
    - name: Create dpadmin user
      user:
        name: dpadmin
        shell: /bin/bash
        create_home: yes
        password: "{{ dpadmin_password | password_hash('sha512') }}"
        state: present

    - name: Give passwordless sudo access
      copy:
        dest: /etc/sudoers.d/dpadmin
        content: |
          dpadmin ALL=(ALL) NOPASSWD: ALL
        owner: root
        group: root
        mode: '0440'
